Repository 3rd-wanted-pre-onboarding-teamA/gameDuo-Wanted-A, pull requests merged in 2022-07, with the labels that each got.

#12 Feature: Redis Congig file 생성
  app.js
  db/redisConfig.js
  services/raid.js
Labels: feature

#15 Feature: 보스레이드상태 조회 api 로직 구현
  app.js
  controllers/bossRaid.controller.js
  db/gameduo_boss_raid_pve.sql
  db/redisConfig.js
  routes/bossRaid.router.js
  routes/index.js
  routes/user.router.js
  services/bossRaid.service.js
Labels: feature

#17 Feat: 보스레이드 랭킹조회
  app.js
  config.js
  controllers/bossRaid.controller.js
  models/rankingInfo.model.js
  routes/bossRaid.router.js
  services/bossRaid.service.js
  services/raid.js
Labels: feature

#21 보스레이드 시작 및 종료
  controllers/bossRaid.controller.js
  routes/bossRaid.router.js
  services/bossRaid.service.js
Labels: feature

#22 게임 종료시 유저 데이터 및 랭킹 업데이트 기능 추가
  controllers/bossRaid.controller.js
  services/bossRaid.service.js
Labels: feature

#23 보스레이드 기능 리팩토링
  controllers/bossRaid.controller.js
  services/bossRaid.service.js
Labels: Refactoring

#26 Refactor: 보스레이드 시작 및 종료 로직 수정, raidStatus 만료시간 설정
  controllers/bossRaid.controller.js
  db/redisConfig.js
  services/bossRaid.service.js
  utils/getStaticData.js
  utils/response.js
Labels: Refactoring

#27 Refactor: status 형식 수정
  controllers/bossRaid.controller.js
  utils/getStaticData.js
Labels: Refactoring

#28 Fix: 보스레이드 상태 조회 시 userId 반환하도록 변경
  services/bossRaid.service.js
Labels: Refactoring

#29 Refactor: 에러 처리 코드 수정
  controllers/bossRaid.controller.js
  services/bossRaid.service.js
Labels: Refactoring

#30 Feature: user 생성 및 조회
  controllers/user.controller.js
  dump.rdb
  routes/user.router.js
  services/user.service.js
  utils/response.js
Labels: feature

#31 코드 리팩토링 및 수정
  controllers/bossRaid.controller.js
  services/bossRaid.service.js
  utils/getStaticData.js
  utils/response.js
  utils/sql.js
Labels: Refactoring

#32 Feat: jest 환경 설정
  package-lock.json
  package.json
Labels: feature

#35 Test: 보스레이드 상태 조회 테스트
  tests/bossRaid.spec.js
Labels: TDD

#36 Test: 보스레이드 랭킹 조회 테스트
  tests/bossRaid.spec.js
Labels: TDD

#38 Refactor: 랭킹 재설정하는 부분 utils로 이동
  app.js
  controllers/bossRaid.controller.js
  utils/topRankerToCache.js
Labels: Refactoring

#39 Refactor: 보스레이드 종료 로직 수정
  controllers/bossRaid.controller.js
  services/bossRaid.service.js
Labels: Refactoring
